//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Interwaly
    {
        public long id { get; set; }
        public string nazwa { get; set; }
        public int wartosc { get; set; }
    }
}
