//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthWebApi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PP_testEntities : DbContext
    {
        public PP_testEntities()
            : base("name=PP_testEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Pojazdy> Pojazdies { get; set; }
        public virtual DbSet<Przejazdy_fs> Przejazdy_fs { get; set; }
        public virtual DbSet<Tagi> Tagis { get; set; }
        public virtual DbSet<Uzytkownicy> Uzytkownicies { get; set; }
        public virtual DbSet<Interwaly> Interwalies { get; set; }
    }
}
