//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Przejazdy_fs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Przejazdy_fs()
        {
            this.Tagis = new HashSet<Tagi>();
        }
    
        public System.Guid id_przejazdu { get; set; }
        public long id_uzytk { get; set; }
        public System.DateTime data_przejazdu { get; set; }
        public byte[] dane_przejazdu { get; set; }
        public Nullable<long> id_pojazdu { get; set; }
    
        public virtual Pojazdy Pojazdy { get; set; }
        public virtual Uzytkownicy Uzytkownicy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tagi> Tagis { get; set; }
    }
}
